### ISSUE TITLE
ImportError: No module named 'cm'

### ISSUE THREAD

**Issue by agrapentin** [matplotlib/cmocean#38]
Installing from PyPi did not work, so I installed from github as the following:

```bash
wget https://github.com/matplotlib/cmocean/archive/master.zip
unzip master.zip
pip install --user cmocean-master/
```

Then, the error message on import:

```python
In [1]: import cmocean
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19d3b496f197> in <module>()
----> 1 import cmocean

/Users/andrew/Library/Python/3.5/lib/python/site-packages/cmocean/__init__.py in <module>()
      7 
      8 # from cmocean import *
----> 9 import cm
     10 import tools
     11 import plots

ImportError: No module named 'cm'
```

Nice work on the documentation, looks great!

**Comment by kthyng** [comment]
Ah, sorry about this trouble. I really thought I had gotten it up on PyPI successfully. I will go through the process again and try to get it right.

But, in the meantime, you should be able to install with the following:

```
git clone https://github.com/matplotlib/cmocean.git
cd cmocean
pip install .
```

**Comment by kthyng** [comment]
This is working on PyPI now! For some reason I had to delete the old version I had uploaded because it was being used instead of being hidden. It isn't present there if you search for it, but it seems to be working nonetheless.
