### ISSUE TITLE
cmocean makes unwanted font changes

### ISSUE THREAD

**Issue by mdunphy** [matplotlib/cmocean#45]
The current version of cmocean makes unwanted changes to font sizes/styles. As the purpose of the package is to provide nice color maps, using "import cmocean" to import the color maps should not have any side effects.

It looks like the problem is the mpl.rcParams[...] lines at the top of cmocean/plots.py. Is it possible to reorganise that code such that it does not make any font changes under normal use?

**Comment by kthyng** [comment]
Fixed with @ocehugo's #46/#47
