### ISSUE TITLE
requirements.txt file is missing in 0.2.1

### ISSUE THREAD

**Issue by empet** [matplotlib/cmocean#49]
The  0.2.1 cmocean version cannot be installed with pip because requirements.txt file is not found. I checked  the tar.gz archive and instead of requirements.txt I found a  file, requires.txt. Please fix this issue because cmocean provides amazing colormaps, and users cannot install it.

**Comment by kthyng** [comment]
Does it work now? 

`pip install cmocean`

Just tried to fix it again. I think it works...

**Comment by kthyng** [comment]
I think this is better now, so I am going to close this, but please let me know if you have any issues.

**Comment by empet** [comment]
Yes,  it can be installed now. Thank you very much!!!
