### ISSUE TITLE
Mapping between old and new cmap names?

### ISSUE THREAD

**Issue by alpha-beta-soup** [matplotlib/cmocean#59]
I just noticed that the names of the colormaps have changed. Is there a simple list of old and new colormap names? I'm looking through the commit that affected the documentation, but I just figured that a list would be easier for those in my situation. Alternatively, it would be great if old names still worked, but maybe just emitted a deprecation notice until one more version change; I suddenly found myself with quite a few broken map configurations today.

**Comment by kthyng** [comment]
Yeah, sorry about the name changes. This was a one-time change but I know it is annoying. Here is a list. Also multiple names were previously accepted, but I plan to stick with just a single, lowercase name from now on to be more simple.

Temperature -> thermal
Salinity -> haline
PAR -> solar
ice (new colormap)
Gray -> gray
Oxygen -> oxy
Bathymetry -> deep
Density -> dense
Chlorophyll -> algae
CDOM -> matter
Turbidity -> turbid
Speed -> speed
WaveAmplitude -> amp
WavePeriod -> tempo
Phase -> phase
FreeSurface -> balance
Velocity -> delta
Vorticity -> curl

**Comment by alpha-beta-soup** [comment]
Thanks for the list!
