### ISSUE TITLE
Import cmocean does not import plots

### ISSUE THREAD

**Issue by fischcheng** [matplotlib/cmocean#60]
Thanks for the great work. It's a wonderful module!

I tried installing cmocean through anaconda and pip, for both python2 and python3. 

However, a simple call `import cmocean` doesn't import the `plots`. So the example shown on the documentation page can't be reproduced. I tried to locate the package, and found that plots.py is there, just not in the `__init__.py`. Was this intentional?

Also, it seems that, cmocean requires the`colorspacious` module, whose dependency has not been checked with either pip or conda. 

Cheers,

**Comment by kthyng** [comment]
Right, plots isn't imported with the package anymore because it included some adjustments to the fonts locally. Though actually it looks like I took that out. In any case, you can just import it with `import cmocean.plots`.

Were you able to install with pip and conda (conda-forge channel)?

**Comment by fischcheng** [comment]
Yes, cmocean was succesfully installed from pip and conda, but when I loaded in cmocean.plots and tried the few examples. It said that the `colorspacious` module is missing.

**Comment by kthyng** [comment]
Hi there. This should be addressed as of the release this summer actually. You can install with 

`pip install "cmocean[plots]"` 

if you want all packages associated with the `plots` function in cmocean.
