### ISSUE TITLE
cmocean colormaps for Tableau

### ISSUE THREAD

**Issue by shaunwbell** [matplotlib/cmocean#63]
I ported the cmocean colormaps to xml flavored preferences file for Tableau and am providing them as a link for you if you want to include them in your database of programs with the colormaps available.

https://github.com/shaunwbell/cmocean_tableau

Cheers

**Comment by tacaswell** [comment]
It is probably worth putting that link in the docs.  Could you open a PR doing that?  There is already a section https://github.com/matplotlib/cmocean/blob/master/docs/source/index.rst#cmocean-available-elsewhere

**Comment by shaunwbell** [comment]
addressed in PR #64
