### ISSUE TITLE
Possible to set number of levels on colormap?

### ISSUE THREAD

**Issue by sophieclayton** [matplotlib/cmocean#79]
Hopefully I'm not missing something obvious here. I often set the number of levels when using matplotlib colormaps:
`cmap = plt.get_cmap('jet',10)`
Is there a way to do this with the cmocean colormaps?

**Comment by kthyng** [comment]
Hi! You should be able to get this behavior with:

```
import cmocean
cmap = plt.get_cmap('cmo.thermal', 10)
```

since once you import cmocean, the colormaps are added to the matplotlib registry with the "cmo." prefix.

**Comment by sophieclayton** [comment]
Brilliant! Thanks @kthyng
