### ISSUE TITLE
Future incompatibility with MPL

### ISSUE THREAD

**Issue by neutrinoceros** [matplotlib/cmocean#83]
Just wanted to warn you about the pending deprecation of some functions in the `matplotlib.cm` namespace that are used in cmocean, like `register_cmap`

https://github.com/matplotlib/matplotlib/pull/23668

If it's any help, here's the patch I wrote to adapt to these deprecations in `yt`
https://github.com/yt-project/yt/pull/4089

I can also submit a PR here if you lack time for this.

**Comment by camUrban** [comment]
I'm getting a depreciation warning from Matplotlib when I use cmocean because of `register_cmap`. A bug fix for this issue would be awesome! :smile:

**Comment by neutrinoceros** [comment]
@kthyng any chance you could give a status on this ?

**Comment by kthyng** [comment]
@neutrinoceros So sorry I've been unresponsive! It's hard to find the time for this at the moment. If you do have the bandwidth for a PR I'll be more responsive. Otherwise I'll aim to work on it in the time frame of the next month. Sorry I can't be faster!

**Comment by neutrinoceros** [comment]
I'm still happy to give it a go. I'm going to aim at delivering a PR before next week !

**Comment by kthyng** [comment]
Thanks @neutrinoceros!

**Comment by dstansby** [comment]
Amazing, thanks a lot 😄
